#!/usr/bin/env node
// Publishes the site's photos to Pinterest through the official API v5.
//
// WHY AN API SCRIPT WHEN THE RSS FEED ALREADY PUBLISHES.
//
// Today /rss.xml is auto-published by Pinterest to the "Travel Photography"
// board of the garaynicong account, and it is the ONLY production path. This
// script does not replace it yet, and running both against the same board
// would pin every photo twice. It exists so the API path is written, tested
// and ready the day the app leaves Trial access.
//
// WHAT TRIAL ACCESS MEANS HERE. An app on Trial access cannot create a pin in
// production at all: Pinterest answers 403 code 29 and points at the sandbox.
// So --publish against production is a no-op until Standard access is granted,
// and --sandbox is how the chain gets exercised in the meantime.
//
// NOTHING IS PUBLISHED BY DEFAULT. The script prints what it would send. The
// CLAUDE.md rule has no exception: nothing goes out in Nico's name without his
// word, and --publish is that word, given once per run.
//
//   node pin.mjs --limit 5                     # preview, no API call
//   node pin.mjs --limit 1 --publish           # creates one pin for real
//   node pin.mjs --limit 1 --publish --sandbox # same, against the API sandbox
//   node pin.mjs --limit 1 --publish --fr      # French title, link to /fr/gallery/
//
// Required for --publish: PINTEREST_ACCESS_TOKEN and PINTEREST_BOARD_ID.

import { PrismaClient } from '@prisma/client';

// Trial access is refused on production outright (403, code 29: "Apps with
// Trial access may not create Pins in production"), so the only place this
// chain can be exercised end to end before Standard access is the sandbox.
const SANDBOX = process.argv.includes('--sandbox');
const API = process.env.PINTEREST_API_BASE
  || (SANDBOX ? 'https://api-sandbox.pinterest.com/v5' : 'https://api.pinterest.com/v5');
const SITE = process.env.NEXT_PUBLIC_SITE_URL ?? 'https://photos.nicogaray.com';
const R2 = (process.env.NEXT_PUBLIC_R2_PUBLIC_URL ?? '').replace(/\/$/, '');

const args = process.argv.slice(2);
const opt = (n, d) => { const i = args.indexOf(n); return i >= 0 ? args[i + 1] : d; };
const publish = args.includes('--publish');
const inFrench = args.includes('--fr');
const limit = Number(opt('--limit', '5'));
const boardId = opt('--board', process.env.PINTEREST_BOARD_ID || '');

// Pinterest field ceilings. Longer values are rejected, not truncated, so the
// truncation happens here where it can be done on a word boundary.
const MAX_TITLE = 100;
const MAX_DESC = 800;
const MAX_ALT = 500;

// Trial access allows 300 writes per day per app. Staying far below is not
// only about the quota: a profile that dumps a hundred pins at once reads as
// spam, and Pinterest's own ranking is the first reader.
const DAILY_CAP = 25;

const cut = (s, n) => {
  const t = (s || '').replace(/\s+/g, ' ').trim();
  if (t.length <= n) return t;
  const coupe = t.slice(0, n - 1);
  const espace = coupe.lastIndexOf(' ');
  return (espace > n * 0.6 ? coupe.slice(0, espace) : coupe) + '…';
};

export function buildPin(photo) {
  const title = inFrench ? photo.title : (photo.titleEn || photo.title);
  const desc = inFrench ? photo.description : (photo.descriptionEn || photo.description);
  const place = [photo.city, photo.country].filter(Boolean).join(', ');
  const tags = inFrench
    ? '#photographiedevoyage #paysage #fondecran'
    : '#travelphotography #landscapephotography #wallpaper';
  return {
    title: cut(title, MAX_TITLE),
    // The description carries the picture, not the keywords: place, then the
    // text already written for the site, then a short tag line.
    description: cut([place, desc, tags].filter(Boolean).join('\n\n'), MAX_DESC),
    alt_text: cut([title, place].filter(Boolean).join(' — '), MAX_ALT),
    link: `${SITE}/${inFrench ? 'fr' : 'en'}/gallery/${photo.slug}`,
  };
}

// The vertical 1000x1500 pin image generated by scripts/generate-pins.ts, which
// is what the RSS feed already serves. It is public on R2, so Pinterest can
// fetch it without a signed URL. Falling back to the horizontal preview is
// allowed but gives a pin that performs badly.
export function imageUrl(photo) {
  const key = photo.pinKey || photo.previewKey;
  if (!key || !R2) return '';
  return `${R2}/${key}`;
}

async function call(path, init = {}) {
  const r = await fetch(`${API}${path}`, {
    ...init,
    headers: {
      Authorization: 'Bearer ' + process.env.PINTEREST_ACCESS_TOKEN,
      'content-type': 'application/json',
      ...(init.headers || {}),
    },
  });
  const j = await r.json().catch(() => ({}));
  if (!r.ok) throw new Error(`${path} (${r.status}) : ${JSON.stringify(j).slice(0, 300)}`);
  return j;
}

/**
 * Links already pinned on the board. This is the guard against the double
 * publication the RSS feed makes easy: same photo, same board, two pins.
 */
async function existingLinks() {
  const links = new Set();
  let bookmark = '';
  for (let page = 0; page < 20; page++) {
    const q = new URLSearchParams({ page_size: '100', ...(bookmark ? { bookmark } : {}) });
    const j = await call(`/boards/${boardId}/pins?${q}`);
    for (const p of j.items || []) if (p.link) links.add(String(p.link).split('?')[0]);
    bookmark = j.bookmark || '';
    if (!bookmark) break;
  }
  return links;
}

async function publishOne(photo) {
  const image = imageUrl(photo);
  if (!image) throw new Error('no pin image for ' + photo.slug);
  const body = {
    board_id: boardId,
    ...buildPin(photo),
    media_source: { source_type: 'image_url', url: image },
  };
  const p = await call('/pins', { method: 'POST', body: JSON.stringify(body) });
  return p.id;
}

async function main() {
  if (publish && (!process.env.PINTEREST_ACCESS_TOKEN || !boardId)) {
    console.error('REFUSED: PINTEREST_ACCESS_TOKEN and PINTEREST_BOARD_ID are required for --publish. Nothing was attempted.');
    process.exit(2);
  }
  if (publish && limit > DAILY_CAP) {
    console.error(`REFUSED: ${limit} is above the ${DAILY_CAP} pins/run ceiling this script keeps.`);
    process.exit(2);
  }

  const prisma = new PrismaClient();
  const photos = await prisma.photo.findMany({
    where: { published: true, pinKey: { not: null } },
    select: {
      slug: true, title: true, titleEn: true, description: true, descriptionEn: true,
      city: true, country: true, pinKey: true, previewKey: true,
    },
    orderBy: { createdAt: 'desc' },
    take: limit,
  });
  await prisma.$disconnect();

  const already = publish ? await existingLinks() : new Set();

  console.log(publish
    ? `REAL PUBLICATION of up to ${photos.length} pin(s) on board ${boardId}`
      + ` via ${API}\n`
    : `PREVIEW of ${photos.length} pin(s), no call to Pinterest\n`);

  for (const photo of photos) {
    const pin = buildPin(photo);
    console.log(`--- ${photo.slug}`);
    console.log(`    image : ${imageUrl(photo) || 'MISSING'}`);
    console.log(`    title : ${pin.title}`);
    console.log(`    link  : ${pin.link}`);
    console.log(`    text  : ${pin.description.replace(/\n/g, ' | ').slice(0, 140)}...`);
    if (!publish) continue;
    if (already.has(pin.link)) { console.log('    SKIPPED  already pinned on this board'); continue; }
    try {
      console.log(`    PINNED   id=${await publishOne(photo)}`);
    } catch (e) {
      console.error(`    FAILED   ${e.message}`);
    }
  }
  if (!publish) console.log('\nNothing was published. Add --publish when the text suits you.');
}

main().catch((e) => { console.error('error:', e.message); process.exit(1); });
